### ISSUE TITLE
Path / Slash Errors on WSL Ubuntu

### ISSUE THREAD

**Issue by mjblacker** [WillEhrendreich/Ionide-nvim#1]
**Describe the bug**

I get the following message when loading in to an F# file that is part of a project.

```
Error executing vim.schedule lua callback: ...o/.local/share/nvim/lazy/Ionide-Nvim/lua/ionide/init.lua:1099: Unknown option 'shellslash'
stack traceback:
        [C]: in function '__index'
        ...o/.local/share/nvim/lazy/Ionide-Nvim/lua/ionide/init.lua:1099: in function 'TextDocumentIdentifier'
        ...o/.local/share/nvim/lazy/Ionide-Nvim/lua/ionide/init.lua:1128: in function 'TextDocumentPositionParams'
        ...o/.local/share/nvim/lazy/Ionide-Nvim/lua/ionide/init.lua:1216: in function 'CallFSharpSignature'
        ...o/.local/share/nvim/lazy/Ionide-Nvim/lua/ionide/init.lua:1498: in function ''
        vim/_editor.lua: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

Sometimes I'll get this as well but not sure if it's related to the same issue
```
LSP[ionide]: Error ON_INIT_CALLBACK_ERROR: "vim/fs.lua:0: path: expected string, got nil"
```

Using Lazy to load the extension, fsautocomplete is working/executable.

**Expected behavior**
LSP to load correctly, keeps showing error after any run of the LSP.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04 (WSL2 Windows 10)
 - Neovim version: 0.10.0
 - dotnet SDK version: 8.0
 - mono / .Net Framework version:

**Comment by WillEhrendreich** [comment]
Wow, my first issue. That's exciting. Thanks for using my Ionide!

Ill take a look and see if I can suss out what's happening! Thanks for reporting it.

**Comment by mjblacker** [comment]
Hey Will,

I thought I would have a go at fixing this, here is the pull request #2

**Comment by WillEhrendreich** [comment]
@mjblacker How is it fairing after your pr? I don't seem to have issues on the windows side from what I can tell. Thanks again for that.

**Comment by mjblacker** [comment]
Yep that seems good thanks for the quick merge.
